Better msg and ret code when folder not found
If diario folder is not available print a nicer error message and
returns 1

Signed-off-by: Joao Trindade <trindade.joao@gmail.com>

diff --git a/sysinfoupdate b/sysinfoupdate
--- a/sysinfoupdate
+++ b/sysinfoupdate
@@ -1469,6 +1469,7 @@ if [ -d ${DIARIO} ] ; then
 	esac
     fi
 else
-    echo "Don't exist ${DIARIO} directory, not running"
+    echo "sysinfoupdate: Error '${DIARIO}' directory does not exist. Exiting without running"
+    exit 1
 fi
 
